language: ruby
rvm:
 - '2.3.1'
services:
 - postgresql
script:
 - RAILS_ENV=test xvfb-run -a bundle exec rake db:migrate --trace
 - xvfb-run -a bundle exec rake db:test:prepare
 - xvfb-run -a bundle exec rake

before_script:
 - psql -c 'create database travis_ci_test;' -U postgres
 - cp config/database.yml.travis config/database.yml